name: Publish Markdown Files
env:
  BLOG_REPO: jontstaz/jonte.com.au
  PUBLISH_DIR: blogposts
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: temp_md
      - name: Checkout linked blog starter repo
        uses: actions/checkout@v3
        with:
          path: temp_blog
          repository: ${{ env.BLOG_REPO }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Install obsidian-export
        run: |
          wget https://github.com/zoni/obsidian-export/releases/download/v22.11.0/obsidian-export_Linux-x86_64.bin
          chmod +x obsidian-export_Linux-x86_64.bin
      - name: Create necessary directories
        run: |
          mkdir -p temp_blog/${{ env.PUBLISH_DIR }}
      - name: Run obsidian-export
        run: |
          ./obsidian-export_Linux-x86_64.bin ./temp_md/publish temp_blog/${{ env.PUBLISH_DIR }}
      - name: Commit and push
        run: |
          cd temp_blog
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Update Blog Post MD Files: $(date -u) Commit ${GITHUB_SHA}"
          git push
      - name: Deploy Vercel
        uses: amondnet/vercel-action@v20
        with:
          # TODO: Update Github Secrets with values
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Required
          vercel-args: "--prod" #Optional
